# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lastver.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import sys

class MainWindow(QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 675)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(370, 190, 291, 61))
        self.start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start.setMouseTracking(True)
        self.start.setAutoDefault(False)
        self.start.setDefault(False)
        self.start.setFlat(False)
        self.start.setObjectName("start")
        self.start.clicked.connect(self.go_to_text_insert_window)

        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(370, 430, 291, 61))
        self.exit.setObjectName("exit")
        self.exit.clicked.connect(qApp.quit)

        self.record_tabel = QtWidgets.QPushButton(self.centralwidget)
        self.record_tabel.setGeometry(QtCore.QRect(370, 270, 291, 61))
        self.record_tabel.setObjectName("record_tabel")

        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(370, 350, 291, 61))
        self.settings.setObjectName("settings")

        self.welcome = QtWidgets.QLabel(self.centralwidget)
        self.welcome.setGeometry(QtCore.QRect(270, 80, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.welcome.setFont(font)
        self.welcome.setObjectName("welcome")

        self.how_to_start = QtWidgets.QLabel(self.centralwidget)
        self.how_to_start.setGeometry(QtCore.QRect(390, 160, 241, 16))
        self.how_to_start.setObjectName("how_to_start")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "Старт"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.record_tabel.setText(_translate("MainWindow", "Таблица рекордов"))
        self.settings.setText(_translate("MainWindow", "Настройки"))
        self.welcome.setText(_translate("MainWindow", "Добро пожаловать в клавиатурный тренажер!"))
        self.how_to_start.setText(_translate("MainWindow", "Для начала тренировки нажмите Старт"))

    def go_to_text_insert_window(self):
        self.open_report = ReportForm.Report(self.lineEdit_user.text(), self.lineEdit_passwd.text())    #передаём в конструктор значения lineEdit_user и lineEdit_passwd
        self.open_report.show()

class Window2(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1042, 675)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1042, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

def application():
    app = QApplication(sys.argv)
    window = MainWindow()

    window.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    application()